### ISSUE TITLE
How to use this images as base image on a windows host

### ISSUE THREAD

**Issue by jkroepke** [microsoft/windows-host-process-containers-base-image#11]
Hi,

I would like to know, how I can use this image as base image and build containers on a Windows host system? I would like to run e2e test and docker build on the same machine.

Currently, this images requires [buildkit](https://github.com/microsoft/windows-host-process-containers-base-image#build-with-buildkit), but buildkit doesn't work on Windows yet.

**Comment by jsturtevant** [comment]
This image can only be used with [HostProcess Containers](https://kubernetes.io/docs/tasks/configure-pod-container/create-hostprocess-pod/).  It will not work with process isolated containers like windows server core or nano server.

Buildkit does have some early support for windows: https://github.com/microsoft/Windows-Containers/issues/34#issuecomment-1980236129.  

What e2e tests are you trying to run?

**Comment by jkroepke** [comment]
> What e2e tests are you trying to run?

On my CI, I have 3 three jobs:

Build application, test application, package application. All three steps running on a Windows host.

The application I would like to build is an go application and must run as HostProcess container.

Currently, I'm building typical nanoserver based image with docker build on that same Windows machine where I run the build and test before.

Know, I would like to the change the base image from nanoserver to the host process images, but currently I'm unable to do that on a Windows host.

**Comment by jkroepke** [comment]
Works, thanks

**Comment by jkroepke** [comment]
FYI: I finally implement this in our CI, however it does not. Windows hccshim throws unknown error on push step
